version: '3.7'

services:

  api:
    container_name: api
    restart: always
    build: 
      context: .
      dockerfile: ./docker/python/Dockerfile
    env_file:
      - ./docker/python/python.dev.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    volumes:
      - ./api:/var/www
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:13.2-alpine
    user: ${CURRENT_USER}
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: britecore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: britecore
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 5431:8080