# Generated by Django 3.1.7 on 2021-02-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "risk",
            },
        ),
        migrations.CreateModel(
            name="RiskCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "risk_category",
            },
        ),
        migrations.CreateModel(
            name="RiskField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=128)),
                ("required", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "risk_field",
            },
        ),
        migrations.CreateModel(
            name="RiskFieldType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "db_table": "risk_field_type",
            },
        ),
        migrations.CreateModel(
            name="RiskRiskField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="risk.risk"
                    ),
                ),
                (
                    "risk_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="risk.riskfield"
                    ),
                ),
            ],
            options={
                "db_table": "risk_risk_field",
            },
        ),
        migrations.AddField(
            model_name="riskfield",
            name="risk_field_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="risk.riskfieldtype"
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="risk_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="risk.riskcategory"
            ),
        ),
        migrations.AddField(
            model_name="risk",
            name="risk_fields",
            field=models.ManyToManyField(
                through="risk.RiskRiskField", to="risk.RiskField"
            ),
        ),
    ]
